name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: true
      matrix:
        # ubuntu-16.04 == cross-compilation for Windows
        os: [ubuntu-16.04, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies [Cross - Windows]
      if: ${{ matrix.os == 'ubuntu-16.04' }}
      run: |
        sudo apt install mingw-w64 pkg-config
        
        # SDL2
        curl -s http://libsdl.org/release/SDL2-2.0.12.tar.gz | tar -zxvf-
        cd SDL2-*
        ./configure --prefix=/usr/x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-sdl2-config=no
        make
        sudo make install
        cd ..

        # Boost
        wget https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2
        tar -jxvf boost*.tar.bz2
        cd boost_1_72_0/
        echo "using gcc : : x86_64-w64-mingw32-g++ ;" > user-config.jam
        ./bootstrap.sh
        sudo ./b2 --prefix=/usr/x86_64-w64-mingw32 --with-system --with-filesystem \
          --user-config=user-config.jam toolset=gcc target-os=windows \
          variant=debug link=shared threading=multi address-model=64 install
        cd ..
    - name: Dependencies [macOS]
      if: ${{ runner.os == 'MacOS' }}
      run: brew install sdl2 boost cmake
    - name: Dependencies [Linux]
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install libasound2-dev libsdl2-dev libboost-filesystem-dev libgtk2.0-dev cmake

    - name: Build submodules [Unix]
      if: ${{ matrix.os != 'ubuntu-16.04' }}
      run: ./build-submodules.sh

    - name: Make [Cross - Windows]
      if: ${{ matrix.os == 'ubuntu-16.04' }}
      run: prefix=/usr/x86_64-w64-mingw32 CROSS_COMPILE=x86_64-w64-mingw32- make
    - name: Make [Unix]
      if: ${{ runner.os != 'Windows' }}
      run: make

    - name: What did this generate?
      run: find .
